spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=postgres
spring.datasource.password=postgres

# JWT Secret Key
jwt.secret-key=your-secret-key